language: ruby
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install:
script: jekyll build

branches:
  only:
    - master


notifications:
  slack:
    # on_success: always
    # on_failure: never
    rooms:
      # - hbcdigital:BAtbJggqijzhCUrMoe2CzAJG#front-end
      # - hbcdigital:BAtbJggqijzhCUrMoe2CzAJG#random
      # only to @designfirst
      - hbcdigital:BAtbJggqijzhCUrMoe2CzAJG 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
