language: ruby
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install:
script: jekyll build

branches:
  only:
    - master

notifications:
  slack:
    on_success: always
    # on_failure: never
    template:
      - "Kudos to %{author} for contributing to the Tech Blog! \nTheir PR <%{pull_request_url}|#%{pull_request_number}> has %{result} build. \nWhy not give them some help merging it!"
    rooms:
      - hbcdigital:BAtbJggqijzhCUrMoe2CzAJG#evangelism
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci dashboard, marked secure
  keep-history: true
  on:
    branch: master
