#
###################################
# Site wide configuration
####################################
#
title: HBC Digital
tagline: "Engineering the Retail Experience"
tagline-2: "Since 1670"
email: evangelism@hbc.com
avatar: hbc-digital-logo.svg
description: > # this means to ignore newlines until "baseurl:"
  We power the website and mobile experiences for Saks, 
  Saks Off Fifth, Gilt, Lord & Taylor and The Bay.
baseurl: "" # the subpath of your site, e.g. blog
url: "" #the base hostname & protocol for your site. 
twitter: hbcdigital
facebook: hbcdigital
github: hbc-tech
linkedin: hbc_digital
instagram: hbcdigital

#google analytics
# google_analytics: UA-83021339-1
google_analytics: UA-106560024-1

#
###################################
# Jekyll configuration
####################################
#
timezone: EST
markdown: kramdown
permalink: pretty
# permalink: /:categories/:year/:month/:day/:title

paginate: 7
paginate_path: "/insights/:num/"

autopages:
  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: false

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - docs
  - node_modules
  - gulpfile.js

# Plugin settings
plugins:
  - jekyll-feed
  - octopress-autoprefixer
  - jekyll-sitemap
  - jekyll-paginate
