#
###################################
# Site wide configuration
####################################
#
title: HBC Digital
email: pops@gilt.com
description: > # this means to ignore newlines until "baseurl:"
  We power the website and mobile experiences for Saks, 
  Saks Off Fifth, Gilt, Lord & Taylor and The Bay.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          EST
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - assets/sass

# Plugin settings
gems:
  - jekyll-feed
  - octopress-autoprefixer
  - jekyll-feed
  - jekyll-sitemap

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: HBC Digital
  avatar: hbc-digital-logo.svg
  job: "Engineering the Retail Experience"
  bio: "Since 1670."
  email: pops@gilt.com
  disqus-shortname:
  twitter: hbcdigital
  facebook: hbcdigital
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gilt
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: hbc_digital
  skype: #username
  xing: #username
  instagram: hbcdigital
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
